name: CI
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Run test
      env:
        ESMETA_HOME: ${{ github.workspace }}
      run: sbt basicTest
  lint:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check code format
      run: sbt formatCheck
