name: CI
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21
        cache: sbt

    - name: Setup SBT
      uses: sbt/setup-sbt@v1

    - name: Fetch all tags from ecma262
      env:
        ESMETA_HOME: ${{ github.workspace }}
      run:
        cd ecma262 && git fetch --tags --depth=1

    - name: Run test
      env:
        ESMETA_HOME: ${{ github.workspace }}
      run: sbt basicTest || (cat tests/detail && exit 1)

    - name: Report status
      if: failure()
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  lint:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21
        cache: sbt

    - name: Setup SBT
      uses: sbt/setup-sbt@v1

    - name: Check code format
      run: sbt formatCheck

    - name: Report status
      if: failure()
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
